2020-05-04 00:14:20,315 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 00:14:25,390 ERROR: Exception on /logout [GET] [in /Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/microblog/app/routes.py", line 50, in logout
    return redirect(url_for('/index'))
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2020-05-04 00:15:04,799 ERROR: Exception on /login [POST] [in /Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/microblog/app/routes.py", line 42, in login
    next_page = url_for('/index')
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2020-05-04 07:27:44,771 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 07:29:39,337 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 07:30:58,407 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 07:34:46,530 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 07:45:08,565 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 07:45:59,207 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-04 13:17:24,079 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 13:22:11,677 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 13:23:36,971 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 13:25:00,842 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 13:25:48,450 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 13:53:51,918 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:23:59,126 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:24:03,655 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:24:31,961 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:27:12,704 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:28:18,089 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:34:28,278 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 14:48:08,394 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 15:35:32,247 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 15:49:32,218 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 16:07:08,238 INFO: Microblog startup [in /Users/zhangbai/microblog/app/__init__.py:47]
2020-05-05 16:07:20,750 ERROR: Exception on /login [POST] [in /Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/microblog/app/routes.py", line 37, in login
    return redirect(url_for('/login'))
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/zhangbai/microblog/flask_env/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/login'. Did you mean 'login' instead?
